version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - "3000:80"
    depends_on:
    - sql_server

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"